### ISSUE TITLE
ammo update for combat-trainer

### ISSUE THREAD

**Issue by TegCross** [elanthia-online/dr-scripts#6996]
Currently line 3398, could you please add marble as an ammo type from Droughtman's and from the Cup It shop at Hollow Eve? I did a quick check of the ammo from the shop and it looks like everything else was added except for 'tile'. I added both in the line below if you don't care where it goes. Thank you very much!
https://elanthipedia.play.net/Cup_It_(2)

ammo_pattern = "(?<ammo>arrow|bolt|stone shard|shard|rock|sphere|clump|marble|tile|coral|fist|holder|lump|patella|pellet|pulzone|quadrello|quarrel|quill|stone|stopper|verretto|blowgun dart|crumb|spine|mantrap spike|tiny dragon|icicle|fang|scale|grey-black spike|bacon strip|page|naga|thorn|fragment|talon|cork|button|core|pebble|geode|stub|pit|thimble|doorknob|cone|bell|hunk|piece|present|sleighbell|sprig|star|toy|spiral)s?"

**Comment by MahtraDR** [comment]
Closing this as resolved by #6997 Please reopen if that isn't the case.
