### ISSUE TITLE
[script] [athletics.lic] add buff routine

### ISSUE THREAD

**Issue by Kiriawen** [elanthia-online/dr-scripts#7004]
Can we move the buff routine that checks for the athletics waggle to be done each loop?

I've been having issues with my athletics spell dropping mid climb practice causing the script to hang indefinitely because the climb became too difficult.

Checking the buff each loop would see that it dropped and recast it before attempting again.

**Comment by MahtraDR** [comment]
I'm not seeing where athletics.lic buffs anything...

**Comment by Kiriawen** [comment]
ok, then can we _add_ a buff check for the athletics waggle?

**Comment by MahtraDR** [comment]
I can, and it's easy, but that will then create the potential for the problem you described originally. If the buff is active when Athletics starts, but then drops... you'd potentially be stuck.

**Comment by Kiriawen** [comment]
that's why I originally asked it to be checked each loop.  I haven't come across any athletics run that takes longer than 10 minutes to do an individual loop so even if we're talking minimum time you should have enough to complete a full loop.  Then it's up to the user to ensure they have their recast set appropriately so that if there is not enough time to complete an additional loop it recasts.

**Comment by MahtraDR** [comment]
There isn't one loop... each different climbing target is its own thing. The simplest we can do here is add a `buff athletics` routine at startup, and it'd be on the user to ensure it lasts the full duration... Otherwise I'd have to add the check to every single climbing target.

**Comment by Kiriawen** [comment]
Better than the nothing it currently has?
